name = "CLWN SMP"
author = "ClownsProd"
version = "1.ll.1-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f45426daf70c214581ce696fae93e7a118a3daac9d0ecc8ec8168598bc92337"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
