name = "CLWN SMP"
author = "ClownsProd"
version = "1.ll.1-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "742fa63b127eee6f135b9ee7ca95a22423405121f2d5969e2b1d6b710ad12f71"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
