name = "CLWN SMP"
author = "ClownsProd"
version = "1.ll.1-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea6822147b734b991ac0c2d09f4eb02e294294ef058dd7ffd26d15ac95f9359f"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
